# Generated by Django 3.2.9 on 2021-12-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_auto_20211213_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='Account',
        ),
    ]
